Prettier and CaptainCommand
Luke-Bytes/TeamsDiscordBot pull request #3
Opened 2024-10-09 00:04 UTC by Luke-Bytes

/captain set [discord] [team]

-Must be registered player
-Adds you to the team colour and sets isCaptain true
-Removes previous captain if they exist

2024-10-09 02:10 UTC, 99-i requested changes
looked fine, but RoleCommand.ts contains another implementation of CaptainCommand?

2024-10-09 02:10 UTC, 99-i commented on src/commands/RoleCommand.ts
should this file be deleted?

2024-10-09 09:24 UTC, Luke-Bytes commented on src/commands/CaptainCommand.ts
> +  }
Let's add to Utils, it probably can be reused later

2024-10-09 09:24 UTC, Luke-Bytes commented on src/commands/RoleCommand.ts
Reverted now

2024-10-09 09:27 UTC, Luke-Bytes commented on src/commands/CaptainCommand.ts
> +      }
In reality I think this won't happen as teams won't be assigned until a definitive captain has started picking teams but it's still an edge case we can fix I'll add something for that

2024-10-10 01:14 UTC, Luke-Bytes commented on src/commands/CaptainCommand.ts
> +      }
I realised if you wanted to change the colour of the captain it borked stuff, I think every edge case is handled now (switching  captains between players and teams related)

2024-10-10 20:05 UTC, 99-i approved these changes

2024-10-10 20:24 UTC, merged